version: "3.9"

services:
    postgres:
      image: postgres
      container_name: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - ./csvs:/var/lib/postgresql/csvs/
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - '5432:5432'
      networks:
        - backend

    predict:
      build:
        dockerfile: predict/Dockerfile.predict
      container_name: predict
      command: uvicorn app.main:app --host 0.0.0.0
      env_file:
        - .env
      volumes:
        - ./data:/data
      ports:
        - "8000:8000"
      networks:
        - frontend
      depends_on:
        - postgres

    preprocess:
      build:
        dockerfile: preprocess/Dockerfile.preprocess
      container_name: preprocess
      command: uvicorn app.main:app --host 0.0.0.0
      env_file:
        - .env
      # volumes:
      #   - ./data:/data
      expose:
        - "8000"
      networks:
        - backend
        - frontend
      depends_on:
        - postgres

networks:
  backend:
    name: backend
  frontend:
    name: frontend
