version: "3.9"

services:
    postgres:
        image: postgres
        container_name: postgres
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    predict:
        build:
          dockerfile: predict/Dockerfile.predict
        container_name: predict
        command: uvicorn app.main:app --host 0.0.0.0
        env_file:
          - .env
        volumes:
          - ./data:/data
        ports:
          - "8000:8000"
        depends_on:
          - postgres
volumes:
  db:
    driver: local